[program:apels-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/apels/artisan queue:work --sleep=3 --tries=3 --timeout=120 --queue=default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/apels/storage/logs/worker.log
stopwaitsecs=3600
